default: &default
  adapter: postgresql
  encoding: utf8
  pool: 5
  reaping_frequency: 10
  username: postgres
  host: <%= ENV.fetch('DATABASE_HOST', 'localhost') %>
  template: template0

development:
  <<: *default
  database: made_in_heaven_development

test: &test
  <<: *default
  database: made_in_heaven_test
